import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import BootstrapClient from '@/components/BootstrapClient'
import 'bootstrap/dist/css/bootstrap.min.css'

import '../scss/style.scss'
import './globals.css'
// import './globals.css';
import ReactQueryProvider from '@/providers/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div>{children}</div>
        </ReactQueryProvider>
        <BootstrapClient />
      </body>
    </html>
  )
}
