import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'

import ReactQueryProvider from '@/providers/ReactQueryProvider'
import '@/styles/index.scss'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable}`}>
        <ReactQueryProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
